(() => {
  "use strict";

  const english = {
    "brand-sub": "App · Time & flex balance", "nav-benefits": "Benefits", "nav-features": "Features", "nav-pricing": "BeeWork Pro", "nav-download": "Download", "nav-cta": "Check availability", "home": "Home",
    "eyebrow": "BeeWork App", "headline": "Your time. Clearly in view.", "subheadline": "The native time and flex-balance tracker for iPhone, iPad and Apple Watch – from the first minute to the end of the day.", "hero-primary": "Check availability", "hero-secondary": "Learn more", "trust-1": "✓ Local & private", "trust-2": "✓ Apple ecosystem", "trust-3": "✓ German & English", "hero-card-title": "Your end of day at a glance", "hero-card-copy": "Target hours, time balance and your expected finish in one clear flow.",
    "benefits-title": "Time tracking that thinks ahead", "benefits-lead": "BeeWork brings the workday together in a calm, easy-to-understand flow.", "benefit-1-title": "Live time tracking", "benefit-1-copy": "Clock in and out to the second – with multiple work blocks and activities per day.", "benefit-2-title": "Flex balance & time account", "benefit-2-copy": "Target time, actual time and your balance stay visible for the day, week and month.", "benefit-3-title": "Smart end of day", "benefit-3-copy": "See when you reach your daily target time – including flex balance.", "benefit-4-title": "Automatic at work", "benefit-4-copy": "Set work locations on a map and get smart reminders when arriving or leaving.", "benefit-5-title": "Always at hand", "benefit-5-copy": "Widgets, Live Activities and Dynamic Island show the active workday right where you need it.", "benefit-6-title": "Apple Watch & Siri", "benefit-6-copy": "Your status stays in sync – and Shortcuts let you clock in or out without opening the app.",
    "gallery-title": "BeeWork in everyday life", "gallery-lead": "Insights into time tracking, salary, vacation planning and the app's other tools.",
    "features-title": "Everything for a clear workday", "features-lead": "The most important tools stay exactly where they help in everyday work.", "feature-1-title": "Time tracking", "feature-1-copy": "Track working time flexibly and add corrections safely.", "feature-1-chip-1": "Work & breaks", "feature-1-chip-2": "Multiple blocks", "feature-1-chip-3": "Reopen day", "feature-2-title": "Time account", "feature-2-copy": "Daily, weekly and monthly balances are calculated automatically.", "feature-2-chip-1": "Target & actual time", "feature-2-chip-2": "Plus & minus hours", "feature-2-chip-3": "Manual corrections", "feature-3-title": "Smart end of day", "feature-3-copy": "BeeWork automatically calculates your expected end of day.", "feature-3-chip-1": "Weekly balance", "feature-3-chip-2": "Break rules", "feature-3-chip-3": "Finish forecast", "feature-4-title": "Automations", "feature-4-copy": "Work locations, reminders and live status support you without detours.", "feature-4-chip-1": "Geofencing", "feature-4-chip-2": "Live Activities", "feature-4-chip-3": "Widgets", "feature-5-title": "Apple integration", "feature-5-copy": "From your wrist to Siri, time tracking stays in sync.", "feature-5-chip-1": "Apple Watch", "feature-5-chip-2": "Siri & Shortcuts", "feature-5-chip-3": "CloudKit", "feature-6-title": "Analytics & export", "feature-6-copy": "Evaluate long-term developments clearly and export reports.", "feature-6-chip-1": "Statistics", "feature-6-chip-2": "PDF & PNG", "feature-6-chip-3": "Salary calculator",
    "pricing-title": "BeeWork Pro", "pricing-lead": "More automation, deeper analytics and unlimited history.", "pricing-monthly": "Monthly", "pricing-yearly": "Yearly", "pricing-lifetime": "Lifetime", "pricing-available": "In the App Store", "pricing-flexible": "Subscribe flexibly.", "pricing-popular": "BeeWork Pro", "pricing-yearly-copy": "For the long-term overview.", "pricing-lifetime-copy": "One-time purchase, if available.", "pricing-note": "Current prices and available options are shown directly in the App Store.",
    "download-title": "Get notified about BeeWork", "download-lead": "The App Store link will be added as soon as BeeWork is available.", "download-badge": "Availability coming soon", "download-fineprint": "Your data remains on your device or syncs through iCloud.", "setup-title": "Your workday, your overview", "setup-1": "Track working time to the second", "setup-2": "Calculate flex balance automatically", "setup-3": "Plan your end of day ahead", "setup-button": "Back to top",
    "faq-lead": "Short answers about BeeWork.", "faq-1-q": "Which devices does BeeWork support?", "faq-1-a": "BeeWork is designed for iPhone and iPad and also includes an Apple Watch app. There is no standalone macOS app.", "faq-2-q": "How does Smart end of day work?", "faq-2-a": "BeeWork calculates an expected end of day from target time, tracked time, breaks and, if desired, your flex or weekly balance.", "faq-3-q": "Are breaks included?", "faq-3-a": "Yes. Breaks are included in the calculation; BeeWork also takes German working-time rules into account.", "faq-4-q": "Can BeeWork remind me at work?", "faq-4-a": "Yes. With Core Location and geofencing, BeeWork can remind you to clock in or start tracking after your confirmation.", "faq-5-q": "Which languages are available?", "faq-5-a": "BeeWork supports German and English. The language can be changed directly in the app.",
    "footer-copy": "Working time in clear view.", "footer-privacy": "Privacy", "footer-terms": "Terms of use", "footer-legal": "Legal notice", "footer-support": "Support", "footer-rights": " BeeWork. All rights reserved."
  };

  const german = Object.fromEntries([...document.querySelectorAll("[data-i18n]")].map((node) => [node.dataset.i18n, node.textContent.trim()]));
  const apply = () => {
    const isEnglish = localStorage.getItem("site_language") === "en";
    const copy = isEnglish ? english : german;
    document.querySelectorAll("[data-i18n]").forEach((node) => { if (copy[node.dataset.i18n]) node.textContent = copy[node.dataset.i18n]; });
    document.title = isEnglish ? "BeeWork – Time Tracking & Flex Balance for iOS" : "BeeWork – Arbeitszeit, Gleitzeit & Feierabend für iOS";
    document.documentElement.lang = isEnglish ? "en" : "de";
  };
  apply();
  document.getElementById("langToggle")?.addEventListener("click", () => window.setTimeout(apply, 0));
})();
